### ISSUE TITLE
단위 테스트 스터디 - 4주차

### ISSUE THREAD

**Issue by kdg0209** [kyoungsun/realizers#12]
### 진도
- 06장 단위 테스트 스타일
- 07장 가치있는 단위 테스트를 위한 리팩터링

### 일정
- 2023.11.02(목) 12:30 ~ 14:00

**Comment by 200okrunner** [comment]
### 요약 정리
* [06장 단위 테스트 스타일](https://github.com/kyoungsun/realizers/blob/main/unit-testing-book/kks/06%EC%9E%A5-%EB%8B%A8%EC%9C%84-%ED%85%8C%EC%8A%A4%ED%8A%B8-%EC%8A%A4%ED%83%80%EC%9D%BC.md)
* [07장 가치있는 단위 테스트를 위한 리팩터링](https://github.com/kyoungsun/realizers/blob/main/unit-testing-book/kks/07%EC%9E%A5-%EA%B0%80%EC%B9%98-%EC%9E%88%EB%8A%94-%EB%8B%A8%EC%9C%84-%ED%85%8C%EC%8A%A4%ED%8A%B8%EB%A5%BC-%EC%9C%84%ED%95%9C-%EB%A6%AC%ED%8C%A9%ED%84%B0%EB%A7%81.md)

### 질문하고 싶은 내용
* 데이터베이스에 데이터를 저장하는 것은 통신 기반 테스트가 필요한가?
* 우리 시스템에서 도메인 이벤트를 사용하는 방식으로 리팩토링하면 좋을 것 같은 코드가 있는가?

**Comment by yooseung20** [comment]
**질문하고 싶은 내용**
- 7장에 서술된 ‘복잡한 코드와 도메인 유의성을 갖는 코드가 단위 테스트에서 가장 이롭다’라는 문장의 뜻은,  해당 코드를 테스트 했을 때 최소 비용으로 최대 가치를 끌어낼 수 있다는 해석할 수 있는가?
- domain event vs application event 어떤 경우에 사용하는게 좋을까?
